# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Aumenta a memória máxima da JVM para 8GB e define codificação UTF-8
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8

# Ativa o cache do Gradle para acelerar builds repetidos
org.gradle.caching=true

# Ativa o uso do daemon para manter a JVM viva entre builds
org.gradle.daemon=true

# Ativa a configuração sob demanda (ótimo para projetos com muitos módulos)
org.gradle.configureondemand=true

# Ativa execução paralela (somente se os módulos forem bem desacoplados)
org.gradle.parallel=true

# Força uso do AndroidX
android.useAndroidX=true

# Define estilo oficial de código Kotlin
kotlin.code.style=official

# Ativa R classes não transitivas (melhora performance e modularidade)
android.nonTransitiveRClass=true
