package com.vald3nir.toolkit.auth

const val AUTH_LIB_PARAM_GOOGLE_SERVER_CLIENT_ID = "AUTH_LIB_PARAM_GOOGLE_SERVER_CLIENT_ID"
const val AUTH_LIB_PARAM_IMAGE_LOGO = "AUTH_LIB_PARAM_IMAGE_LOGO"
const val AUTH_LIB_PARAM_PRIMARY_COLOR = "AUTH_LIB_PARAM_PRIMARY_COLOR"
const val AUTH_LIB_PARAM_INT_INVALID = -1
const val AUTH_LIB_PARAM_LOGIN_RESPONSE = "AUTH_LIB_PARAM_LOGIN_RESPONSE"

enum class AuthLibLoginResponseType { SUCCESS, USE_TRIAL }